FORM_1040:
  categories:
    primary_tax_documents:
      - type: FORM_1040
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 1040"
      - type: W2
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form W-2"
      - type: FORM_1099NEC
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 1099-NEC"
      - type: FORM_1099K
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 1099-K"

  required:
    - type: CONDITIONAL_INCOME
      description: Additional Income Documentation
      priority: high
      conditions:
        foreign_income:
          trigger: "has_foreign_income == true"
          category: "international_documents"
          required_docs:
            - type: FOREIGN_BANK_STATEMENTS
              metadata:
                retention_years: 6
                fbar_required: true
            - type: FOREIGN_TAX_RETURNS
              metadata:
                retention_years: 7
                treaty_benefits: check_required

    - type: W2
      description: W-2 Wage and Tax Statement
      priority: high
      metadata:
        expiration: "tax_year_end"
        retention_period: "7_years"
        formats: ["pdf", "jpg", "png"]
        max_size: 10485760  # 10MB
        retention_years: 7
        irs_form_association: "Form W-2"
        purpose: "income_verification"
        special_handling: "sensitive_personal_information"
      validation:
        required_fields: ["employer_id", "wages", "federal_tax_withheld"]
        format: "standard_w2"
        field_patterns:
          employer_id: "^\d{2}-\d{7}$"
          wages: "^\d+(\.\d{2})?$"
        date_ranges:
          tax_year: "current_year"
        cross_validation:
          total_withholding: ["federal_tax_withheld", "state_tax_withheld"]

    - type: IDENTIFICATION
      description: Valid government-issued ID
      priority: high
      metadata:
        expiration: "id_expiration_date"
        formats: ["pdf", "jpg", "png"]
        max_size: 5242880  # 5MB
        retention_years: 7
        purpose: "identity_verification"
        special_handling: "sensitive_personal_information"
      validation:
        required_fields: ["id_number", "expiration_date"]
        format: "government_id"
        field_patterns:
          id_number: "^[A-Z0-9-]+$"
          expiration_date: "^20\d{2}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])$"
        date_ranges:
          expiration: "future_date"

    - type: SSN_CARD
      description: Social Security Card or ITIN documentation
      priority: high
      validation:
        required_fields: ["ssn_number"]
        format: "ssn"

  optional:
    - type: DEPENDENT_SSN
      description: Dependent Social Security Cards
      priority: medium
      validation:
        required_fields: ["dependent_ssn"]
        format: "ssn"

EDUCATION_DOCUMENTS:
  categories:
    education_expenses:
      - type: FORM_1098T
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 1098-T"

STATE_DOCUMENTS:
  categories:
    state_credits:
      - type: STATE_CREDIT
        priority: high
        metadata:
          retention_years: 7
          requires_state_verification: true
          state_specific_rules: true

INTERNATIONAL_DOCUMENTS:
  categories:
    foreign_income:
      - type: FORM_2555
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 2555"
      - type: FORM_8938
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 8938"

CHARITABLE_CONTRIBUTIONS:
  categories:
    noncash_donations:
      - type: FORM_8283
        priority: high
        metadata:
          retention_years: 7
          irs_form_association: "Form 8283"

SCHEDULE_REQUIREMENTS:
  SCHEDULE_A:
    required:
      - type: ITEMIZED_DEDUCTIONS
        priority: high
        metadata:
          retention_years: 7

  SCHEDULE_B:
    required:
      - type: INTEREST_DIVIDENDS
        priority: high
        metadata:
          retention_years: 7

  SCHEDULE_C:
    required:
      - type: BUSINESS_INCOME
        priority: high
        metadata:
          retention_years: 7

  SCHEDULE_D:
    required:
      - type: CAPITAL_GAINS
        priority: high
        metadata:
          retention_years: 7

  SCHEDULE_E:
    required:
      - type: RENTAL_INCOME
        priority: high
        metadata:
          retention_years: 7

  SCHEDULE_F:
    required:
      - type: FARM_INCOME
        priority: high
        metadata:
          retention_years: 7
