# Document Categories
PRIMARY_DOCUMENTS:
  description: "Essential tax documents required for filing"
  priority: high
  retention: 7
  validation_rules:
    - required_fields: ["document_id", "tax_year", "amount"]
    - format_checks: ["pdf", "jpg", "png"]
    - max_size: 10485760  # 10MB
    - cross_validation: ["total_income", "tax_withheld"]
    - document_quality: ["legible", "complete", "unaltered"]

INCOME_DOCUMENTS:
  description: "Income-related documentation"
  priority: high
  retention: 7
  subcategories:
    W2:
      required_fields: ["employer_id", "wages", "federal_tax_withheld"]
      validation_rules:
        - field_patterns:
            employer_id: "^\d{2}-\d{7}$"
            wages: "^\d+(\.\d{2})?$"
    1099_NEC:
      required_fields: ["payer_tin", "recipient_tin", "nonemployee_compensation"]
      validation_rules:
        - field_patterns:
            payer_tin: "^\d{2}-\d{7}$"
            nonemployee_compensation: "^\d+(\.\d{2})?$"
    1099_K:
      required_fields: ["payer_tin", "gross_amount", "transaction_count"]
      validation_rules:
        - field_patterns:
            gross_amount: "^\d+(\.\d{2})?$"
            transaction_count: "^\d+$"
    FARM_INCOME:
      required_fields: ["farm_name", "ein", "farm_address"]
      validation_rules:
        - field_patterns:
            ein: "^\d{2}-\d{7}$"
            income: "^\d+(\.\d{2})?$"
        - cross_validation: ["total_farm_income", "expenses"]

EXPENSE_DOCUMENTS:
  description: "Expense and deduction documentation"
  priority: medium
  retention: 3
  subcategories:
    RECEIPTS:
      required_fields: ["date", "amount", "vendor"]
      validation_rules:
        - date_format: "YYYY-MM-DD"
        - amount_format: "^\d+(\.\d{2})?$"
    INVOICES:
      required_fields: ["invoice_number", "date", "amount"]

ASSET_DOCUMENTS:
  description: "Asset-related documentation"
  priority: medium
  retention: permanent
  subcategories:
    PROPERTY:
      required_fields: ["property_id", "purchase_date", "cost_basis"]
    VEHICLE:
      required_fields: ["vin", "purchase_date", "cost"]

INTERNATIONAL_DOCUMENTS:
  description: "International tax-related documents"
  priority: high
  retention: 7
  subcategories:
    FORM_2555:
      required_fields: ["foreign_earned_income", "tax_home", "residence"]
      validation_rules:
        - field_patterns:
            foreign_earned_income: "^\d+(\.\d{2})?$"
    FORM_8938:
      required_fields: ["foreign_assets", "max_value"]
      validation_rules:
        - threshold: 50000
    FBAR:
      required_fields: ["account_number", "max_value", "institution"]
      validation_rules:
        - threshold: 10000
    FORM_1116:
      required_fields: ["foreign_tax_paid", "foreign_income"]
      validation_rules:
        - field_patterns:
            foreign_tax_paid: "^\d+(\.\d{2})?$"
    FOREIGN_INCOME:
      required_fields: ["country", "income_amount", "tax_paid"]
      validation_rules:
        - currency_validation: true
        - exchange_rate_required: true
    FOREIGN_ASSETS:
      required_fields: ["asset_type", "value", "country"]
      validation_rules:
        - threshold_check: "value > 50000"
        - currency_validation: true

CREDIT_DOCUMENTS:
  description: "Tax credit documentation"
  priority: high
  retention: 7
  subcategories:
    FORM_8863:
      required_fields: ["institution_name", "student_name", "qualified_expenses"]
      validation_rules:
        - field_patterns:
            qualified_expenses: "^\d+(\.\d{2})?$"
    FORM_5695:
      required_fields: ["property_address", "improvement_type", "cost"]
      validation_rules:
        - field_patterns:
            cost: "^\d+(\.\d{2})?$"
    FORM_2441:
      required_fields: ["provider_name", "provider_tax_id", "expenses"]
      validation_rules:
        - field_patterns:
            expenses: "^\d+(\.\d{2})?$"
    FORM_5329:
      required_fields: ["distribution_amount", "early_withdrawal_reason"]
      validation_rules:
        - field_patterns:
            distribution_amount: "^\d+(\.\d{2})?$"
    FORM_8606:
      required_fields: ["contribution_amount", "basis"]
      validation_rules:
        - field_patterns:
            contribution_amount: "^\d+(\.\d{2})?$"
    FORM_3520:
      required_fields: ["gift_amount", "donor_information"]
      validation_rules:
        - field_patterns:
            gift_amount: "^\d+(\.\d{2})?$"
    FORM_4562:
      required_fields: ["asset_description", "cost_basis", "depreciation_method"]
      validation_rules:
        - field_patterns:
            cost_basis: "^\d+(\.\d{2})?$"
    EDUCATION_CREDITS:
      required_fields: ["institution", "student_name", "amount_paid"]
      validation_rules:
        - field_patterns:
            amount_paid: "^\d+(\.\d{2})?$"
    ENERGY_CREDITS:
      required_fields: ["improvement_type", "cost", "date_installed"]
      validation_rules:
        - qualified_improvements_check: true

EDUCATION_DOCUMENTS:
  description: "Education-related documentation"
  priority: high
  retention: 7
  subcategories:
    FORM_1098T:
      required_fields: ["institution_name", "student_name", "tuition_amount"]
      validation_rules:
        - field_patterns:
            tuition_amount: "^\d+(\.\d{2})?$"

STATE_DOCUMENTS:
  description: "State-specific documentation"
  priority: high
  retention: 7
  subcategories:
    STATE_CREDIT:
      required_fields: ["state_code", "credit_type", "amount"]
      validation_rules:
        - state_specific_validation: true
