# Category-specific Metadata Configuration
METADATA_FIELDS:
  COMMON:
    - field: document_id
      type: string
      required: true
      format: "^DOC-[0-9A-Z]{8}$"
      
    - field: tax_year
      type: integer
      required: true
      validation: "current_year - 7 <= value <= current_year"
      
    - field: submission_date
      type: date
      required: true
      validation: "value <= current_date"
    
  INCOME_DOCUMENTS:
    - field: income_type
      type: enum
      values: ["wages", "self_employment", "rental", "investment", "farm_income"]
      required: true
    
    - field: amount
      type: decimal
      required: true
      validation: "value >= 0"
    
    - field: tax_withheld
      type: decimal
      required: false
      validation: "value >= 0"

  EXPENSE_DOCUMENTS:
    - field: expense_category
      type: enum
      values: ["business", "rental", "medical", "education"]
      required: true
    
    - field: payment_method
      type: enum
      values: ["cash", "check", "credit", "electronic"]
      required: true
    
    - field: business_purpose
      type: string
      required: false
      max_length: 500

  ASSET_DOCUMENTS:
    - field: asset_type
      type: enum
      values: ["real_estate", "vehicle", "equipment", "investment"]
      required: true
    
    - field: acquisition_date
      type: date
      required: true
      validation: "value <= current_date"
    
    - field: cost_basis
      type: decimal
      required: true
      validation: "value > 0"

  INTERNATIONAL_DOCUMENTS:
    - field: country
      type: string
      required: true
      format: "^[A-Z]{2}$"
      validation: "valid_country_code"
    
    - field: currency_code
      type: string
      required: true
      format: "^[A-Z]{3}$"
      validation: "valid_currency_code"
      
    - field: exchange_rate
      type: decimal
      required: true
      validation: "value > 0"

RETENTION_RULES:
  DEFAULT:
    duration: "7"
    unit: years
    start_from: "tax_year_end"
    exceptions:
      - document_type: "asset_purchase_records"
        duration: "permanent"
      - document_type: "business_formation"
        duration: "permanent"

  PERMANENT:
    - asset_purchase_records
    - business_formation_documents
    - tax_basis_documentation

  CUSTOM:
    expense_receipts:
      duration: 3
      unit: years
    
    bank_statements:
      duration: 7
      unit: years
    
    tax_returns:
      duration: 7
      unit: years

SECURITY_CLASSIFICATION:
  HIGH_SENSITIVITY:
    - document_types:
        - social_security_documents
        - tax_returns
        - bank_statements
        - foreign_accounts
      requirements:
        encryption: required
        access_control: strict
        audit_logging: required

  MEDIUM_SENSITIVITY:
    - document_types:
        - expense_receipts
        - income_statements
        - business_records
      requirements:
        encryption: required
        access_control: standard
        audit_logging: enabled

  LOW_SENSITIVITY:
    - public_records
    - marketing_materials
